import pytest
from mcp.server.mcpserver.exceptions import ToolError
from test_host_scripts import client_setup

from sysadmin_mcp.mcp_execution import ExecutionBridge
from sysadmin_mcp.server import create_mcp_server


class TestBridge:
    __test__ = False

    def __init__(self, client, token):
        self.client = client
        self.headers = {'authorization': 'Bearer ' + token}

    async def call(self, path, body=None):
        response = self.client.request('GET' if body is None else 'POST', '/api/mcp' + path,
                                       headers=self.headers, json=body)
        if response.status_code >= 400:
            raise ToolError(response.json()['detail'])
        return response.json()


def pair(client, headers):
    response = client.post('/api/scripts/mcp-connection', headers=headers)
    assert response.status_code == 200, response.text
    return response.json()['token']


@pytest.mark.asyncio
@pytest.mark.parametrize('mode', ['guided', 'autonomous_lab'])
async def test_actual_mcp_tool_dispatch_respects_guided_approval(tmp_path, mode):
    client, headers, password, _, calls, executor = client_setup(tmp_path, mode)
    token = pair(client, headers)
    server = create_mcp_server(executor, execution_bridge=TestBridge(client, token))
    scope = await server.call_tool('get_execution_scope', {})
    assert scope.structured_content['mode'] == mode
    prepared = await server.call_tool('prepare_host_script', {
        'host': 'lab', 'title': 'Nginx task generated by the MCP client',
        'script': 'print("task")', 'verification': 'print("checks")',
    })
    assert not prepared.is_error
    job = prepared.structured_content
    assert calls == []
    args = {'job_id': job['id'], 'digest': job['digest']}
    with pytest.raises(ToolError, match='operator review'):
        await server.call_tool('run_host_script', args)
    assert not calls
    # Only the web operator can approve, including in Autonomous Lab mode.
    endpoint = f"/api/scripts/jobs/{job['id']}/run"
    body = {'digest': job['digest'], 'password': password}
    response = client.post(endpoint, headers=headers, json=body)
    assert response.json()['state'] == 'verified'
    assert client.post(endpoint, headers=headers, json=body).status_code == 400
    evidence = await server.call_tool('get_host_script_job', {'job_id': job['id']})
    assert evidence.structured_content['result']['verification']['exit_status'] == 0
    assert len(calls) == 1
    tools = {t.name: t for t in await server.list_tools()}
    assert tools['run_host_script'].annotations.destructive_hint is True
    assert not tools['run_host_script'].annotations.read_only_hint
    assert not {'arm_mode', 'approve_host_script'} & tools.keys()


def test_tokens_cannot_arm_approve_or_outlive_scope(tmp_path):
    client, headers, password, _, calls, _ = client_setup(tmp_path, 'autonomous_lab')
    assert client.post('/api/scripts/mcp-connection').status_code == 403
    first = pair(client, headers)
    second = pair(client, headers)
    assert client.get('/api/mcp/scope', headers={'authorization': 'Bearer ' + first}).status_code == 401
    token_headers = {'authorization': 'Bearer ' + second}
    assert client.get('/api/mcp/scope', headers=token_headers).status_code == 200
    assert client.get('/api/mcp/scope').status_code == 401  # Cookie alone cannot delegate.
    client.post('/api/authority/pause', headers=headers)
    assert client.get('/api/mcp/scope', headers=token_headers).status_code == 403
    client.post('/api/authority/resume', headers=headers)
    assert client.get('/api/mcp/scope', headers=token_headers).status_code == 200
    client.post('/api/authority/stop', headers=headers)
    client.post('/api/authority/arm', headers=headers, json={
        'mode': 'autonomous_lab', 'hosts': ['lab'], 'capabilities': ['host_scripts'],
        'duration_minutes': 15, 'action_budget': 1, 'concurrency': 1, 'password': password})
    assert client.get('/api/mcp/scope', headers=token_headers).status_code == 401
    client.cookies.clear()
    assert client.post('/api/authority/stop', headers=token_headers).status_code == 401
    assert not calls


def test_logout_revokes_connection(tmp_path):
    client, headers, _, _, _, _ = client_setup(tmp_path, 'guided')
    token = pair(client, headers)
    client.post('/api/auth/logout', headers=headers)
    assert client.get('/api/mcp/scope', headers={'authorization': 'Bearer ' + token}).status_code == 401


@pytest.mark.parametrize('url', ['https://example.com', 'http://127.0.0.1@evil.test',
                               'http://localhost/api', 'http://localhost?token=leak'])
def test_bridge_rejects_nonlocal_or_ambiguous_destinations(url):
    with pytest.raises(ValueError):
        ExecutionBridge(url, 'secret')
