'use client';

import Link from 'next/link';
import { useCallback, useEffect, useState } from 'react';
import { Clock3, KeyRound, Laptop, LoaderCircle, ShieldCheck, UserRound, X } from 'lucide-react';
import { AppNav } from '@/components/app-nav';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { apiFetch } from '@/lib/api';

type Identity={username:string;role:string;csrf_token:string};
type Session={session_id:string;client_label:string;created_at:string;last_seen_at:string;expires_at:string;current:boolean};
type Event={id:number;occurred_at:string;event_type:string;session_id:string|null};
const labels:Record<string,string>={login_success:'Signed in',login_failure:'Failed sign-in',login_throttled:'Sign-in throttled',password_changed:'Password changed',logout:'Signed out',session_revoked:'Session revoked',session_expired:'Session expired'};
const when=(value:string)=>new Date(value).toLocaleString();

export default function AccountPage(){
 const [identity,setIdentity]=useState<Identity|null>(null),[sessions,setSessions]=useState<Session[]>([]),[events,setEvents]=useState<Event[]>([]),[busy,setBusy]=useState(true),[error,setError]=useState('');
 const load=useCallback(async()=>{setBusy(true);setError('');try{const me=await apiFetch('/api/auth/me');if(!me.ok)return;const who=await me.json() as Identity;sessionStorage.setItem('sentinel-csrf',who.csrf_token);setIdentity(who);const [sessionResponse,eventResponse]=await Promise.all([apiFetch('/api/auth/sessions'),apiFetch('/api/auth/events?limit=30')]);if(!sessionResponse.ok||!eventResponse.ok)throw new Error('Could not load account security data.');setSessions(await sessionResponse.json() as Session[]);setEvents(await eventResponse.json() as Event[])}catch(reason){setError(reason instanceof Error?reason.message:'The local agent API is offline.')}finally{setBusy(false)}},[]);
 useEffect(()=>{void load()},[load]);
 async function revoke(session:Session){if(session.current||!confirm(`Revoke ${session.client_label}?`))return;setError('');const response=await apiFetch('/api/auth/sessions/revoke',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({session_id:session.session_id})});if(!response.ok){setError('Could not revoke that session.');return}await load()}
 return <main className="min-h-screen bg-background text-foreground"><header className="flex min-h-16 flex-wrap items-center justify-between gap-3 border-b px-6 py-3"><div><h1 className="font-semibold">Account security</h1><p className="text-xs text-muted-foreground">Identity, sessions, and recent access activity</p></div><AppNav/></header><section className="mx-auto max-w-5xl space-y-6 p-6">{error&&<p role="alert" className="rounded-xl bg-red-400/10 p-4 text-sm text-red-200">{error}</p>}{busy?<p className="flex items-center gap-2 text-sm text-muted-foreground"><LoaderCircle className="animate-spin"/>Loading account security…</p>:<><div className="grid gap-4 md:grid-cols-3"><article className="rounded-2xl border bg-card p-5"><UserRound className="size-5 text-emerald-300"/><p className="mt-4 text-xs text-muted-foreground">Signed in as</p><p className="font-medium">{identity?.username}</p><Badge variant="outline" className="mt-2 capitalize">{identity?.role}</Badge></article><article className="rounded-2xl border bg-card p-5"><Clock3 className="size-5 text-sky-300"/><p className="mt-4 font-medium">Session policy</p><p className="mt-1 text-sm text-muted-foreground">30 minutes idle · 8 hours maximum</p></article><article className="rounded-2xl border bg-card p-5"><KeyRound className="size-5 text-amber-300"/><p className="mt-4 font-medium">Password</p><p className="mt-1 text-sm text-muted-foreground">Use 12–256 characters.</p><Button asChild variant="outline" size="sm" className="mt-3"><Link href="/change-password">Change password</Link></Button></article></div><div><h2 className="mb-3 font-medium">Active sessions</h2><div className="space-y-3">{sessions.map(session=><article key={session.session_id} className="flex flex-wrap items-center gap-4 rounded-2xl border bg-card p-4"><Laptop className="size-5 text-muted-foreground"/><div className="min-w-48 flex-1"><div className="flex items-center gap-2"><p className="text-sm font-medium">{session.client_label}</p>{session.current&&<Badge className="bg-emerald-400/10 text-emerald-300">Current</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">Last active {when(session.last_seen_at)} · Expires {when(session.expires_at)}</p></div>{!session.current&&<Button type="button" variant="outline" size="sm" onClick={()=>void revoke(session)}><X/>Revoke</Button>}</article>)}</div></div><div><h2 className="mb-3 font-medium">Recent security activity</h2><div className="overflow-hidden rounded-2xl border bg-card">{events.length===0?<p className="p-4 text-sm text-muted-foreground">No security activity recorded.</p>:events.map(event=><div key={event.id} className="flex items-center gap-3 border-b p-4 last:border-b-0"><ShieldCheck className="size-4 text-muted-foreground"/><p className="flex-1 text-sm">{labels[event.event_type]??event.event_type}</p><time className="text-xs text-muted-foreground">{when(event.occurred_at)}</time></div>)}</div></div></>}</section></main>;
}
