'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Label } from '@/components/ui/label'; import { apiFetch } from '@/lib/api';
export default function ChangePassword() {
 const router=useRouter(); const [current,setCurrent]=useState(''); const [next,setNext]=useState(''); const [confirm,setConfirm]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
 useEffect(()=>{void apiFetch('/api/auth/me').then(async r=>{if(r.ok){const d=await r.json() as {csrf_token:string};sessionStorage.setItem('sentinel-csrf',d.csrf_token)}})},[]);
 async function submit(e:FormEvent){e.preventDefault();if(next!==confirm){setError('New passwords do not match.');return}setBusy(true);setError('');const r=await apiFetch('/api/auth/change-password',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({current_password:current,new_password:next})});const d=await r.json() as {detail?:string};setBusy(false);if(!r.ok){setError(d.detail??'Could not change password');return}router.replace('/');}
 return <main className="grid min-h-screen place-items-center bg-background p-6"><section className="w-full max-w-md rounded-2xl border border-border bg-card p-6"><h1 className="text-xl font-semibold">Create a secure password</h1><p className="mt-2 text-sm text-muted-foreground">Required before diagnostics are unlocked. Use at least 12 characters.</p><form onSubmit={submit} className="mt-6 space-y-4"><Label className="grid gap-2">Current password<Input type="password" autoComplete="current-password" value={current} onChange={e=>setCurrent(e.target.value)}/></Label><Label className="grid gap-2">New password<Input type="password" minLength={12} autoComplete="new-password" value={next} onChange={e=>setNext(e.target.value)}/></Label><Label className="grid gap-2">Confirm new password<Input type="password" minLength={12} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)}/></Label>{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}<Button className="w-full" disabled={busy}>Change password and continue</Button></form></section></main>;
}
