'use client';
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { ArrowLeft,Clock3,LoaderCircle,Server } from 'lucide-react';
import { useParams } from 'next/navigation';
import { AppNav } from '@/components/app-nav';
import { Badge } from '@/components/ui/badge';
import { apiFetch } from '@/lib/api';
type Point={captured_at:string;status:string;cpu_percent:number|null;memory_percent:number|null;disk_percent:number|null;message:string};
type Detail={name:string;hostname:string;thresholds:{cpu_percent:number;memory_percent:number;disk_percent:number};history:Point[]};
export default function HostPage(){const params=useParams<{host:string}>(),[detail,setDetail]=useState<Detail|null>(null),[error,setError]=useState('');useEffect(()=>{void (async()=>{try{const me=await apiFetch('/api/auth/me');if(!me.ok)return;const identity=await me.json() as {csrf_token:string};sessionStorage.setItem('sentinel-csrf',identity.csrf_token);const response=await apiFetch(`/api/fleet/hosts/${encodeURIComponent(params.host)}?limit=100`);const data=await response.json() as Detail&{detail?:string};if(!response.ok)throw new Error(data.detail??'Host not found.');setDetail(data)}catch(reason){setError(reason instanceof Error?reason.message:'Could not load host history.')}})()},[params.host]);return <main className="min-h-screen bg-background"><header className="flex min-h-16 items-center justify-between border-b px-6"><div><h1 className="font-semibold">Host details</h1><p className="text-xs text-muted-foreground">Thresholds and recent observations</p></div><AppNav/></header><section className="mx-auto max-w-6xl space-y-6 p-6"><Link href="/fleet" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4"/>Fleet</Link>{error&&<p className="rounded-xl bg-red-400/10 p-4 text-red-200">{error}</p>}{!detail&&!error&&<p className="flex gap-2 text-sm text-muted-foreground"><LoaderCircle className="animate-spin"/>Loading history…</p>}{detail&&<><div className="flex items-center gap-3 rounded-2xl border bg-card p-5"><Server className="text-emerald-300"/><div><h2 className="font-medium">{detail.name}</h2><p className="text-xs text-muted-foreground">{detail.hostname}</p></div><div className="ml-auto flex gap-2"><Badge variant="outline">CPU {detail.thresholds.cpu_percent}%</Badge><Badge variant="outline">RAM {detail.thresholds.memory_percent}%</Badge><Badge variant="outline">Disk {detail.thresholds.disk_percent}%</Badge></div></div><div className="rounded-2xl border bg-card p-5"><h2 className="font-medium">Health trend</h2><p className="text-xs text-muted-foreground">Newest observation first · up to 100 snapshots</p><div className="mt-5 space-y-3">{detail.history.map((p,i)=><div key={`${p.captured_at}-${i}`} className="grid items-center gap-3 rounded-xl bg-muted/30 p-3 md:grid-cols-[180px_90px_1fr]"><p className="flex gap-2 text-xs text-muted-foreground"><Clock3 className="size-3"/>{new Date(p.captured_at).toLocaleString()}</p><Badge variant="outline" className="w-fit">{p.status}</Badge><div className="grid grid-cols-3 gap-2 text-xs"><span>CPU {p.cpu_percent??'—'}%</span><span>RAM {p.memory_percent??'—'}%</span><span>Disk {p.disk_percent??'—'}%</span></div></div>)}{!detail.history.length&&<p className="text-sm text-muted-foreground">Run a fleet refresh to create the first snapshot.</p>}</div></div></>}</section></main>}
